require: 
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/**/*'
    - 'docs/**/*'
    - 'docsrc/**/*'
    - 'node_modules/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'test/**/*'
  TargetRubyVersion: 2.7.1

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ClassStructure:
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - instance_methods
      - protected_methods
      - private_methods

Layout/HeredocIndentation:
  EnforcedStyle: powerpack
  
# Trailing white space is meaningful in code examples
Layout/TrailingWhitespace:
  AllowInHeredoc: true

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Metrics/BlockLength:
  Exclude: 
    - 'config/routes.rb'

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search

Performance/UnfreezeString:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/MixinUsage:
  Exclude:
  - 'bin/*'